Algoritmo "semnome"

Var
// Seção de Declarações das variáveis 

x:inteiro
total,total2,total3:logico

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
x <- 5
//total <- (x = 10) ou (x <= 20)
//escreval(total)

//total2 <- (x > 0) ou (x <> 3)
//escreval(total2)

total <- nao (x = 10)
total2 <- nao (x >= 2)
total3 <- nao ((x <= 20) e (x = 10))
escreval(total)
escreval(total2)
escreval(total3)


Fimalgoritmo