Algoritmo "senha_fixa"
// Disciplina   : [Linguagem e Lógica de Programação]

Var
// Seção de Declarações das variáveis 

senha:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


escreva("Digite a senha:")
leia(senha)

enquanto senha <> 2002 faca
   escreva("Senha Invalida! Tente novamente: ")
   leia(senha)

fimenquanto

escreva("Acesso Permitido!")





Fimalgoritmo