Algoritmo "semnome"


Var
// Seção de Declarações das variáveis 
c,f: real
resp:caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 



repita
    escreval("Digite a temperatura em Celsius: ")
    leia(c)
    f <- 9.0 * c / 5.0 + 32.0
    escreval("Equivalente em Fahrenheit: ",F:3:1 )
    escreval("Deseja repetir (s/n)? ")
    leia(resp)
ate resp <> "s"



Fimalgoritmo